version: '3.9'

services:
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=video_annotation

volumes:
  pgdata: